site_name: HULL
docs_dir: ./src
site_url: https://github.com/vidispine/hull
theme:
  name: material
validation:
  links:
    absolute_links: relative_to_docs
nav:
  - About: 'README.md'
  - Changelog: 'CHANGELOG.md'
  - History: 'HISTORY.md'
  - Docs: "hull/files/doc"
